import React from "react";

const RightSide = () => {
  return (
    <aside className="p-4">
      <div className="text-center">
        <button type="button" className="btn btn-primary w-100">
          Write for me
        </button>
      </div>
      <div className="d-flex justify-content-end px-4 mt-3">
        <p className="text-danger" role="button">
          Clear
        </p>
      </div>
      <div className="overflow-scroll" style={{ height: "500px" }}>
        <div className="shadow p-2 mb-5 bg-body rounded d-flex justify-content-center align-items-center mt-5">
          <p className="text-primary px-2">Copy</p>
          <p className="border-start px-2">
            As artificial intelligence continues to evolve, it is becoming
            increasingly capable of generating original and insightful content.
            This blog post is a prime example; the title was generated by AI
            within 10 seconds. AI is quickly becoming a powerful tool for
            content creators and marketers alike.
          </p>
        </div>
        <div className="shadow p-2 mb-5 bg-body rounded d-flex justify-content-center align-items-center mt-5">
          <p className="text-primary px-2">Copy</p>
          <p className="border-start px-2">
            As artificial intelligence continues to evolve, it is becoming
            increasingly capable of generating original and insightful content.
            This blog post is a prime example; the title was generated by AI
            within 10 seconds. AI is quickly becoming a powerful tool for
            content creators and marketers alike.
          </p>
        </div>
        <div className="shadow p-2 mb-5 bg-body rounded d-flex justify-content-center align-items-center mt-5">
          <p className="text-primary px-2">Copy</p>
          <p className="border-start px-2">
            As artificial intelligence continues to evolve, it is becoming
            increasingly capable of generating original and insightful content.
            This blog post is a prime example; the title was generated by AI
            within 10 seconds. AI is quickly becoming a powerful tool for
            content creators and marketers alike.
          </p>
        </div>
        <div className="shadow p-2 mb-5 bg-body rounded d-flex justify-content-center align-items-center mt-5">
          <p className="text-primary px-2">Copy</p>
          <p className="border-start px-2">
            As artificial intelligence continues to evolve, it is becoming
            increasingly capable of generating original and insightful content.
            This blog post is a prime example; the title was generated by AI
            within 10 seconds. AI is quickly becoming a powerful tool for
            content creators and marketers alike.
          </p>
        </div>
      </div>
    </aside>
  );
};

export default RightSide;
